/*==============================================================*/
/* DBMS name:      SAP HANA 1.0 Database                        */
/* Created on:     2017/12/26 23:36:02                          */
/*==============================================================*/


drop sequence PCIF.SEQ_CARD_BIZ_NO cascade;

drop sequence PCIF.SEQ_ENT_AGENT cascade;

drop sequence PCIF.SEQ_ENT_AGENT_AUDIT_FLOW cascade;

drop sequence PCIF.SEQ_ENT_AUDIT_FLOW cascade;

drop sequence PCIF.SEQ_ENT_CERTIFICATE cascade;

drop sequence PCIF.SEQ_ENT_CONTACT cascade;

drop sequence PCIF.SEQ_ENT_CUSTINFO cascade;

drop sequence PCIF.SEQ_ENT_MANAGERINFO cascade;

drop sequence PCIF.SEQ_ENT_OPERATOR cascade;

drop sequence PCIF.SEQ_ENT_ROLE cascade;

drop sequence PCIF.SEQ_ENT_ROLE_RES cascade;

drop sequence PCIF.SEQ_ENT_USER cascade;

drop sequence PCIF.SEQ_ENT_USER_AGREEMENT cascade;

drop sequence PCIF.SEQ_PER_AUTHENTICATION cascade;

drop sequence PCIF.SEQ_PER_BANK_CARD cascade;

drop sequence SEQ_PER_BIZ_CARD_BIND cascade;

drop sequence PCIF.SEQ_PER_BUSI_DEFIN cascade;

drop sequence PCIF.SEQ_PER_CERTIFICATE cascade;

drop sequence PCIF.SEQ_PER_CUST_AGREEMENT cascade;

drop sequence PCIF.SEQ_PER_CUST_AUTHORIZATION cascade;

drop sequence PCIF.SEQ_PER_CUST_TAG cascade;

drop sequence PCIF.SEQ_PER_EMAIL_VERIF_CD_KEY cascade;

drop sequence PCIF.SEQ_PER_EMAIL_VERIF_ID cascade;

drop sequence SEQ_PER_IMG_ACCREDIT cascade;

drop sequence PCIF.SEQ_PER_IMG_INFO cascade;

drop sequence PCIF.SEQ_PER_INDIVIDUAL cascade;

drop sequence PCIF.SEQ_PER_KEY_EVENT cascade;

drop sequence PCIF.SEQ_PER_MANUAL_INTERVENTION cascade;

drop sequence PCIF.SEQ_PER_PARA_MAIN cascade;

drop sequence PCIF.SEQ_PER_RISK_MONITOR cascade;

drop sequence PCIF.SEQ_PER_SMS_VERIF_CD_KEY cascade;

drop sequence PCIF.SEQ_PER_SMS_VERIF_ID cascade;

drop sequence PCIF.SEQ_PER_SYSTEM_TEMP_MESSAGE cascade;

drop sequence PCIF.SEQ_PER_TEMP_INFO cascade;

drop sequence PCIF.SEQ_PER_TRANS_DETAIL cascade;

drop sequence PCIF.SEQ_PER_TRANS_LOG cascade;

drop sequence SEQ_PER_UMANAGEMENT_FLOW cascade;

drop sequence PCIF.SEQ_PER_USER cascade;

drop sequence PCIF.SEQ_PER_USER_AGREEMENT cascade;

drop sequence PCIF.SEQ_PER_USER_CONTACT cascade;

drop sequence PCIF.SEQ_PER_USER_IMG cascade;

drop sequence SEQ_PER_USER_OAUTH_BIND cascade;

drop sequence PCIF.SEQ_PER_WTBK_LOG cascade;

create sequence PCIF.SEQ_CARD_BIZ_NO;

create sequence PCIF.SEQ_ENT_AGENT;

create sequence PCIF.SEQ_ENT_AGENT_AUDIT_FLOW;

create sequence PCIF.SEQ_ENT_AUDIT_FLOW;

create sequence PCIF.SEQ_ENT_CERTIFICATE;

create sequence PCIF.SEQ_ENT_CONTACT;

create sequence PCIF.SEQ_ENT_CUSTINFO;

create sequence PCIF.SEQ_ENT_MANAGERINFO;

create sequence PCIF.SEQ_ENT_OPERATOR;

create sequence PCIF.SEQ_ENT_ROLE;

create sequence PCIF.SEQ_ENT_ROLE_RES;

create sequence PCIF.SEQ_ENT_USER;

create sequence PCIF.SEQ_ENT_USER_AGREEMENT;

create sequence PCIF.SEQ_PER_AUTHENTICATION;

create sequence PCIF.SEQ_PER_BANK_CARD;

create sequence SEQ_PER_BIZ_CARD_BIND;

create sequence PCIF.SEQ_PER_BUSI_DEFIN;

create sequence PCIF.SEQ_PER_CERTIFICATE;

create sequence PCIF.SEQ_PER_CUST_AGREEMENT;

create sequence PCIF.SEQ_PER_CUST_AUTHORIZATION;

create sequence PCIF.SEQ_PER_CUST_TAG;

create sequence PCIF.SEQ_PER_EMAIL_VERIF_CD_KEY;

create sequence PCIF.SEQ_PER_EMAIL_VERIF_ID;

create sequence SEQ_PER_IMG_ACCREDIT;

create sequence PCIF.SEQ_PER_IMG_INFO;

create sequence PCIF.SEQ_PER_INDIVIDUAL;

create sequence PCIF.SEQ_PER_KEY_EVENT;

create sequence PCIF.SEQ_PER_MANUAL_INTERVENTION;

create sequence PCIF.SEQ_PER_PARA_MAIN;

create sequence PCIF.SEQ_PER_RISK_MONITOR;

create sequence PCIF.SEQ_PER_SMS_VERIF_CD_KEY;

create sequence PCIF.SEQ_PER_SMS_VERIF_ID;

create sequence PCIF.SEQ_PER_SYSTEM_TEMP_MESSAGE;

create sequence PCIF.SEQ_PER_TEMP_INFO;

create sequence PCIF.SEQ_PER_TRANS_DETAIL;

create sequence PCIF.SEQ_PER_TRANS_LOG;

create sequence SEQ_PER_UMANAGEMENT_FLOW;

create sequence PCIF.SEQ_PER_USER;

create sequence PCIF.SEQ_PER_USER_AGREEMENT;

create sequence PCIF.SEQ_PER_USER_CONTACT;

create sequence PCIF.SEQ_PER_USER_IMG;

create sequence SEQ_PER_USER_OAUTH_BIND;

create sequence PCIF.SEQ_PER_WTBK_LOG;

